[package]
name = "aneks_app"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "*"
rand = "*"
regex = "1"
reqwest = { version = "0.11", features = ["blocking", "json"] }